name: Link check docs

on: 
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  link_check:
    runs-on: ubuntu-latest
    needs: preview.preview
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List MDX Files
        id: list_mdx_files
        run: |
          curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" |
          jq -r '.[] | select(.filename | endswith(".mdx")) | .filename' > mdx_files.txt

      - name: Display MDX Files
        run: cat mdx_files.txt

      - name: Get deploy preview URL
        id: deploy_preview
        run: |
          DEPLOY_PREVIEW_URL=$(curl -s -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" "https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/deploys" | jq -r '.[0].deploy_url')
          echo "::set-output name=url::$DEPLOY_PREVIEW_URL"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Output Deploy Preview URL
        run: echo "Deploy Preview URL: ${{ steps.deploy_preview.outputs.url }}"

