name: Check docs links

on: [pull_request]

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for deploy preview rebuild
        id: wait-deploy-preview
        run: |
          url="https://deploy-preview-${{ github.event.number }}--apollo-monodocs.netlify.app/"
          timeout=1000  # Timeout in seconds
          start_time=$(date +%s)
          sleep 60
          while true; do
            if curl -s --head "$url" | head -n 1 | grep "HTTP/1.[01] [23].." > /dev/null; then
              echo "$url is accessible."
              break
            fi
            current_time=$(date +%s)
            elapsed_time=$((current_time - start_time))
            if [ $elapsed_time -ge $timeout ]; then
              echo "Timeout reached. $url is not accessible."
              exit 1
            fi
            sleep 30  # Check every 30 sec
          done

      - name: Install link checker
        run: npm install -g linkinator

      - name: Check Links
        id: check_links
        run: linkinator --concurrency 10 --timeout 5000 https://deploy-preview-${{ github.event.number }}--apollo-monodocs.netlify.app/