name: Check docs links

on: [pull_request]

env:
  DEPLOY_PREVIEW_URL: https://deploy-preview-${{ github.event.number }}--apollo-monodocs.netlify.app/

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for deploy preview rebuild
        id: wait-deploy-preview
        run: |
          max_iters=20
          counter=0
          while [[ $counter -lt $max_iters ]]; do
            sleep 60
            if curl -s --head "$DEPLOY_PREVIEW_URL" | head -n 1 | grep "HTTP/1.[01] [23].." > /dev/null; then
              echo "$DEPLOY_PREVIEW_URL is accessible."
              exit 0
            fi
            counter=$((counter+1))
          done
          echo "Timeout reached. $DEPLOY_PREVIEW_URL is not accessible."
          exit 1

      - name: Install link checker
        run: npm install -g linkinator

      - name: Check Links
        id: check_links
        run: linkinator --concurrency 10 --timeout 5000 $DEPLOY_PREVIEW_URL