name: Link check docs

on: [pull_request]

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List MDX Files
        id: list_mdx_files
        run: |
          curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" |
          jq -r '.[] | select(.filename | endswith(".mdx")) | .filename' > mdx_files.txt

      - name: Display MDX Files
        run: cat mdx_files.txt
        